/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexer;

import java.io.*;
import node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.NORMAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 54:
                        {
                            @SuppressWarnings("hiding") Token token = new54(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 55:
                        {
                            @SuppressWarnings("hiding") Token token = new55(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComment(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStringLiteral(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCharLiteral(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEscape(text, line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPlus(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMinus(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMult(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLessThan(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLessThanOrEq(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGreaterThan(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGreaterThanOrEq(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEquals(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAnd(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOr(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNot(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColon(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemicolon(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLPar(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRPar(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBrace(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBrace(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBkt(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBkt(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNotEquals(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEqualTo(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPointer(line, pos); }
    Token new28(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFloatLit(text, line, pos); }
    Token new29(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhiteSpace(text, line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBool(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBreak(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TChar(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConst(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TContinue(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKclass(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDo(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TElse(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFalse(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFloat(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIf(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInt(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNew(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNull(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrivate(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProtected(line, pos); }
    Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPublic(line, pos); }
    Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReturn(line, pos); }
    Token new48(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStatic(line, pos); }
    Token new49(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TString(line, pos); }
    Token new50(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStruct(line, pos); }
    Token new51(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TThis(line, pos); }
    Token new52(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTrue(line, pos); }
    Token new53(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhile(line, pos); }
    Token new54(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVoid(line, pos); }
    Token new55(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentifier(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // NORMAL
            {{9, 9, 1}, {10, 10, 2}, {12, 12, 3}, {13, 13, 4}, {32, 32, 5}, {33, 33, 6}, {34, 34, 7}, {38, 38, 8}, {39, 39, 9}, {40, 40, 10}, {41, 41, 11}, {42, 42, 12}, {43, 43, 13}, {44, 44, 14}, {45, 45, 15}, {46, 46, 16}, {47, 47, 17}, {48, 57, 18}, {58, 58, 19}, {59, 59, 20}, {60, 60, 21}, {61, 61, 22}, {62, 62, 23}, {65, 90, 24}, {91, 91, 25}, {93, 93, 26}, {95, 95, 24}, {97, 97, 24}, {98, 98, 27}, {99, 99, 28}, {100, 100, 29}, {101, 101, 30}, {102, 102, 31}, {103, 104, 24}, {105, 105, 32}, {106, 109, 24}, {110, 110, 33}, {111, 111, 24}, {112, 112, 34}, {113, 113, 24}, {114, 114, 35}, {115, 115, 36}, {116, 116, 37}, {117, 117, 24}, {118, 118, 38}, {119, 119, 39}, {120, 122, 24}, {123, 123, 40}, {124, 124, 41}, {125, 125, 42}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 43}, {12, 32, -2}, },
            {{9, 32, -2}, },
            {{61, 61, 44}, },
            {{0, 9, 45}, {11, 12, 45}, {14, 33, 45}, {34, 34, 46}, {35, 65535, 45}, },
            {{38, 38, 47}, },
            {{32, 32, 48}, {33, 33, 49}, {34, 34, 50}, {35, 35, 51}, {36, 36, 52}, {37, 37, 53}, {38, 38, 54}, {40, 40, 55}, {41, 41, 56}, {42, 42, 57}, {43, 43, 58}, {44, 44, 59}, {45, 45, 60}, {46, 46, 61}, {47, 47, 62}, {48, 57, 63}, {58, 58, 64}, {59, 59, 65}, {60, 60, 66}, {61, 61, 67}, {62, 62, 68}, {63, 63, 69}, {64, 64, 70}, {65, 90, 71}, {91, 91, 72}, {92, 92, 73}, {93, 93, 74}, {94, 94, 75}, {95, 95, 76}, {96, 96, 77}, {97, 122, 78}, {123, 123, 79}, {124, 124, 80}, {125, 125, 81}, {126, 126, 82}, },
            {},
            {},
            {},
            {},
            {},
            {{62, 62, 83}, },
            {{48, 57, 84}, {69, 69, 85}, {101, 101, 86}, },
            {{42, 42, 87}, {47, 47, 88}, },
            {{46, 46, 16}, {48, 57, 18}, },
            {},
            {},
            {{61, 61, 89}, },
            {{61, 61, 90}, },
            {{61, 61, 91}, },
            {{48, 57, 92}, {65, 90, 92}, {95, 95, 92}, {97, 122, 92}, },
            {},
            {},
            {{48, 95, -26}, {97, 110, 92}, {111, 111, 93}, {112, 113, 92}, {114, 114, 94}, {115, 122, 92}, },
            {{48, 95, -26}, {97, 103, 92}, {104, 104, 95}, {105, 107, 92}, {108, 108, 96}, {109, 110, 92}, {111, 111, 97}, {112, 122, 92}, },
            {{48, 110, -29}, {111, 111, 98}, {112, 122, 92}, },
            {{48, 95, -26}, {97, 107, 92}, {108, 108, 99}, {109, 122, 92}, },
            {{48, 95, -26}, {97, 97, 100}, {98, 107, 92}, {108, 108, 101}, {109, 122, 92}, },
            {{48, 95, -26}, {97, 101, 92}, {102, 102, 102}, {103, 109, 92}, {110, 110, 103}, {111, 122, 92}, },
            {{48, 95, -26}, {97, 100, 92}, {101, 101, 104}, {102, 116, 92}, {117, 117, 105}, {118, 122, 92}, },
            {{48, 95, -26}, {97, 113, 92}, {114, 114, 106}, {115, 116, 92}, {117, 117, 107}, {118, 122, 92}, },
            {{48, 100, -35}, {101, 101, 108}, {102, 122, 92}, },
            {{48, 95, -26}, {97, 115, 92}, {116, 116, 109}, {117, 122, 92}, },
            {{48, 103, -30}, {104, 104, 110}, {105, 113, 92}, {114, 114, 111}, {115, 122, 92}, },
            {{48, 110, -29}, {111, 111, 112}, {112, 122, 92}, },
            {{48, 103, -30}, {104, 104, 113}, {105, 122, 92}, },
            {},
            {{124, 124, 114}, },
            {},
            {{9, 32, -2}, },
            {},
            {{0, 65535, -9}, },
            {},
            {},
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{34, 34, 116}, {39, 39, 117}, {92, 92, 118}, {98, 98, 119}, {102, 102, 120}, {110, 110, 121}, {114, 114, 122}, {116, 116, 123}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {{39, 39, 115}, },
            {},
            {{48, 101, -18}, },
            {{43, 43, 124}, {45, 45, 125}, {48, 57, 126}, },
            {{43, 57, -87}, },
            {{0, 41, 127}, {42, 42, 128}, {43, 65535, 127}, },
            {{0, 9, 129}, {10, 10, 130}, {11, 12, 129}, {13, 13, 131}, {14, 65535, 129}, },
            {},
            {},
            {},
            {{48, 122, -26}, },
            {{48, 110, -29}, {111, 111, 132}, {112, 122, 92}, },
            {{48, 100, -35}, {101, 101, 133}, {102, 122, 92}, },
            {{48, 95, -26}, {97, 97, 134}, {98, 122, 92}, },
            {{48, 95, -26}, {97, 97, 135}, {98, 122, 92}, },
            {{48, 95, -26}, {97, 109, 92}, {110, 110, 136}, {111, 122, 92}, },
            {{48, 122, -26}, },
            {{48, 95, -26}, {97, 114, 92}, {115, 115, 137}, {116, 122, 92}, },
            {{48, 107, -32}, {108, 108, 138}, {109, 122, 92}, },
            {{48, 110, -29}, {111, 111, 139}, {112, 122, 92}, },
            {{48, 122, -26}, },
            {{48, 115, -38}, {116, 116, 140}, {117, 122, 92}, },
            {{48, 95, -26}, {97, 118, 92}, {119, 119, 141}, {120, 122, 92}, },
            {{48, 107, -32}, {108, 108, 142}, {109, 122, 92}, },
            {{48, 95, -26}, {97, 104, 92}, {105, 105, 143}, {106, 110, 92}, {111, 111, 144}, {112, 122, 92}, },
            {{48, 95, -26}, {97, 97, 92}, {98, 98, 145}, {99, 122, 92}, },
            {{48, 115, -38}, {116, 116, 146}, {117, 122, 92}, },
            {{48, 95, -26}, {97, 97, 147}, {98, 113, 92}, {114, 114, 148}, {115, 122, 92}, },
            {{48, 104, -108}, {105, 105, 149}, {106, 122, 92}, },
            {{48, 95, -26}, {97, 116, 92}, {117, 117, 150}, {118, 122, 92}, },
            {{48, 104, -108}, {105, 105, 151}, {106, 122, 92}, },
            {{48, 104, -108}, {105, 105, 152}, {106, 122, 92}, },
            {},
            {},
            {{39, 39, 153}, },
            {{39, 39, 153}, },
            {{39, 39, 153}, },
            {{39, 39, 153}, },
            {{39, 39, 153}, },
            {{39, 39, 153}, },
            {{39, 39, 153}, },
            {{39, 39, 153}, },
            {{48, 57, 126}, },
            {{48, 57, 126}, },
            {{48, 57, 126}, },
            {{0, 65535, -89}, },
            {{0, 41, 154}, {42, 42, 128}, {43, 46, 154}, {47, 47, 155}, {48, 65535, 154}, },
            {{0, 65535, -90}, },
            {},
            {{10, 10, 156}, },
            {{48, 107, -32}, {108, 108, 157}, {109, 122, 92}, },
            {{48, 95, -26}, {97, 97, 158}, {98, 122, 92}, },
            {{48, 113, -36}, {114, 114, 159}, {115, 122, 92}, },
            {{48, 114, -101}, {115, 115, 160}, {116, 122, 92}, },
            {{48, 114, -101}, {115, 115, 161}, {116, 116, 162}, {117, 122, 92}, },
            {{48, 100, -35}, {101, 101, 163}, {102, 122, 92}, },
            {{48, 114, -101}, {115, 115, 164}, {116, 122, 92}, },
            {{48, 95, -26}, {97, 97, 165}, {98, 122, 92}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 107, -32}, {108, 108, 166}, {109, 122, 92}, },
            {{48, 95, -26}, {97, 117, 92}, {118, 118, 167}, {119, 122, 92}, },
            {{48, 115, -38}, {116, 116, 168}, {117, 122, 92}, },
            {{48, 107, -32}, {108, 108, 169}, {109, 122, 92}, },
            {{48, 116, -113}, {117, 117, 170}, {118, 122, 92}, },
            {{48, 115, -38}, {116, 116, 171}, {117, 122, 92}, },
            {{48, 104, -108}, {105, 105, 172}, {106, 116, 92}, {117, 117, 173}, {118, 122, 92}, },
            {{48, 114, -101}, {115, 115, 174}, {116, 122, 92}, },
            {{48, 100, -35}, {101, 101, 175}, {102, 122, 92}, },
            {{48, 95, -26}, {97, 99, 92}, {100, 100, 176}, {101, 122, 92}, },
            {{48, 107, -32}, {108, 108, 177}, {109, 122, 92}, },
            {},
            {{0, 41, 178}, {42, 42, 179}, {43, 65535, 178}, },
            {},
            {},
            {{48, 122, -26}, },
            {{48, 95, -26}, {97, 106, 92}, {107, 107, 180}, {108, 122, 92}, },
            {{48, 122, -26}, },
            {{48, 114, -101}, {115, 115, 181}, {116, 122, 92}, },
            {{48, 115, -38}, {116, 116, 182}, {117, 122, 92}, },
            {{48, 104, -108}, {105, 105, 183}, {106, 122, 92}, },
            {{48, 122, -26}, },
            {{48, 100, -35}, {101, 101, 184}, {102, 122, 92}, },
            {{48, 115, -38}, {116, 116, 185}, {117, 122, 92}, },
            {{48, 122, -26}, },
            {{48, 95, -26}, {97, 97, 186}, {98, 122, 92}, },
            {{48, 100, -35}, {101, 101, 187}, {102, 122, 92}, },
            {{48, 104, -108}, {105, 105, 188}, {106, 122, 92}, },
            {{48, 113, -36}, {114, 114, 189}, {115, 122, 92}, },
            {{48, 104, -108}, {105, 105, 190}, {106, 122, 92}, },
            {{48, 109, -99}, {110, 110, 191}, {111, 122, 92}, },
            {{48, 95, -26}, {97, 98, 92}, {99, 99, 192}, {100, 122, 92}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 100, -35}, {101, 101, 193}, {102, 122, 92}, },
            {{0, 65535, -156}, },
            {{0, 41, 154}, {42, 42, 179}, {43, 65535, -130}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 109, -99}, {110, 110, 194}, {111, 122, 92}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 115, -38}, {116, 116, 195}, {117, 122, 92}, },
            {{48, 98, -175}, {99, 99, 196}, {100, 122, 92}, },
            {{48, 98, -175}, {99, 99, 197}, {100, 122, 92}, },
            {{48, 109, -99}, {110, 110, 198}, {111, 122, 92}, },
            {{48, 98, -175}, {99, 99, 199}, {100, 122, 92}, },
            {{48, 95, -26}, {97, 102, 92}, {103, 103, 200}, {104, 122, 92}, },
            {{48, 115, -38}, {116, 116, 201}, {117, 122, 92}, },
            {{48, 122, -26}, },
            {{48, 116, -113}, {117, 117, 202}, {118, 122, 92}, },
            {{48, 100, -35}, {101, 101, 203}, {102, 122, 92}, },
            {{48, 115, -38}, {116, 116, 204}, {117, 122, 92}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 122, -26}, },
            {{48, 100, -35}, {101, 101, 205}, {102, 122, 92}, },
            {{48, 122, -26}, },
            {{48, 100, -35}, {101, 101, 206}, {102, 122, 92}, },
            {{48, 122, -26}, },
            {{48, 99, -153}, {100, 100, 207}, {101, 122, 92}, },
            {{48, 122, -26}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // NORMAL
        {29, 29, 29, 29, 29, 29, 15, -1, -1, -1, 19, 20, 6, 4, 18, 5, 28, 7, -1, 16, 17, 8, 26, 10, 55, 23, 24, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 21, -1, 22, 29, 25, -1, 1, 13, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 27, 28, -1, -1, -1, -1, 9, 12, 11, 55, 55, 55, 55, 55, 55, 36, 55, 55, 55, 40, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 14, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 28, -1, -1, -1, 0, 0, 55, 55, 55, 55, 55, 55, 55, 55, 41, 42, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 3, -1, 0, 0, 30, 55, 32, 55, 55, 55, 37, 55, 55, 43, 55, 55, 55, 55, 55, 55, 55, 51, 52, 54, 55, -1, -1, 31, 35, 33, 55, 38, 39, 55, 55, 55, 55, 55, 55, 55, 53, 55, 55, 55, 46, 47, 48, 49, 50, 55, 44, 55, 34, 55, 45, },

    };*/

    public static class State
    {
        public final static State NORMAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
